config/routes.rb
Box::Application.routes.draw do
  

  get "pages/home"
  get "pages/game"
  get "pages/score"
  get "pages/ajout"

  post "pages/score"
  post "pages/ajout"

  match '/home', :to => 'pages#home'
  match '/ajout', :to => 'pages#ajout'
  match '/game', :to => 'pages#game'
  match '/score', :to => 'pages#score'
  

   root :to => 'pages#home'

end

app/models/new.rb
class New < ActiveRecord::Base
  attr_accessible :contenu, :titre
   	validates :contenu, :presence => true, :uniqueness => true
   	validates :titre, :presence => true
   	
end

app/models/score.rb
class Validation < ActiveModel::Validator
  def validate(record)
    if Score.exists?(:pseudo => record.pseudo) 
    	if  Score.where({ :pseudo => record.pseudo }).last.tries == record.tries 
      		record.errors[:base] << "This person is already there !"
    	end	
    end
  end
end

class Score < ActiveRecord::Base
	attr_accessible :date, :pseudo, :tries

   	validates :pseudo, :presence => true,
   						:length   => { :maximum => 50 }

   	validates :tries, :presence => true,:numericality => { :only_integer => true }
   	validates_with Validation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@titre = "Home"
  end

  def game
    @titre = "Game"
  end

  def ajout
  	@titre = "Ajout"
    @pass = params[:pass]
    @title = params[:titre]
    @contenu = params[:contenu]
  end

  def score
  	@titre = "Score"
  	@pseudo = params[:pseudo]
  	@tries = params[:tries78]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Retourner un titre basé sur la page.
  def titre
    base_titre = "JOD"
    if @titre.nil?
      base_titre
    else
      "#{base_titre} | #{@titre}"
    end
  end

  def active(page)
  	if(@titre==page)
  		'class=active'
  	end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= titre %></title>
    <%= csrf_meta_tag %>
    <%= stylesheet_link_tag "application", :media => "all" %>


  </head>
  <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/fr_FR/all.js#xfbml=1&appId=580923821938111";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
  <body>
    <div class="container-narrow">
      <div class="masthead">
            <ul class="nav nav-pills pull-right">
              <li <%= active('Home') %>><%= link_to "Home", home_path  %></li>
              <li <%= active('Game') %>><%= link_to "Game", game_path  %></li>
              <li <%= active('Score') %>><%= link_to "Score", score_path  %></li>
             <li><div class="fb-like" data-href="https://www.facebook.com/adminjumpordie" data-send="false" data-layout="button_count"  data-show-faces="false" data-font="trebuchet ms"></div></li>
              </ul>
          <h3 class="muted" >Jump Or Die (Bêta)</h3>
      </div>
      <hr>  
      <div class="jumbotron"> 
        <%= yield %>
      </div>
      <hr>
      <div class="footer">
        <p>&copy; Melki 2013</p>
      </div>
    <%= javascript_include_tag "application" %>
    <%= debug(params) if Rails.env.development? %>
    </div> <!--/.container -->
  </body>
</html>

app/views/pages/ajout.html.erb
<h1>Ajout de news</h1>
<% if @pass == "News1993" %>
 <% nouveau = New.new(:titre => @title, :contenu => @contenu) %>
 <% nouveau.save %>
<% end %>

<%= form_tag("/ajout", :method => "post") do %>
  
	<%= password_field_tag 'pass',nil, :placeholder => "Your password", :required => true, :type => "password" %>
  	<br>
	<%= text_field_tag 'titre',nil, :placeholder => "Your title", :required => true %>
  	<br>
	<%= text_area_tag 'contenu',nil, :placeholder =>  "Your news here",:class => "input-xlarge", :rows => 5,:cols => 1000, :required => true %>
  	<br>
	 <%= submit_tag "Let's post this fucking news", :class => "btn" %>
<% end %>

app/views/pages/game.html.erb
<div id="whereItHappens">
	<canvas  id="canvas" width="800" height="400" ></canvas>
<p>The rules are simple, use the <code>spacebar</code> to jump and try to reach the other side of the area.</p>
<p>Use <code name="canvas">enter</code> to play or to pause the game.</p>
</div>
<%= audio_tag("theme.wav", :autoplay => false, :loop => true, :controls => false, :id => "audio") %>

app/views/pages/home.html.erb
<h1>Welcome</h1>
<p><%= link_to "This", game_path  %> is the beta version of a little game developed in javascript using the HTML5 canvas.</p>
<p>As it's still a beta game, new levels will be added every two or three days and the databases will be erased regularly...</p>
<h2>News</h2>
 <% article = New.order("created_at DESC") %>
  <% i=1 %>
  <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Date</th>
                  <th>Title</th>
                  <th>Content</th>
                </tr>
              </thead>
              <tbody>
                <% for s in article %>
                <tr>
                  <td><%= i %></td>
                  <td><%= s.created_at.strftime("%m/%d/%Y") %></td>
                  <td><%= s.titre %></td>
                  <td><%= s.contenu %></td>
                </tr>
                <% i = i + 1 %>
                <% end %>
               </tbody>
            </table>

app/views/pages/score.html.erb
<h1>Leaderboard</h1>
  <% if(request.referer) %>
  <% if(request.referer.split('/').last=="game") %>
  <% nouveau = Score.new(:pseudo => @pseudo, :tries => @tries) %>
  <% nouveau.save %>
  <%  %>
  <% end %>
  <% end %>
  <% score = Score.order("tries ") %>
  <% i=1 %>
  <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Pseudo</th>
                  <th>Number of tries</th>
                  <th>Date</th>
                </tr>
              </thead>
              <tbody>
                <% for s in score %>
                <tr>
                  <td><%= i %></td>
                  <td><%= s.pseudo %></td>
                  <td><%= s.tries %></td>
                  <td><%= s.created_at.strftime("%m/%d/%Y at %I:%M") %></td>
                </tr>
                <% i = i + 1 %>
                <% end %>
               </tbody>
            </table>